version: '3.5'
networks:
    iro_lan:
        driver: bridge
        name: iro_lan
        ipam:
          config:
          - subnet: 172.21.0.0/16

services:
    iro:
        dns:
            - 1.1.1.1
        image: michalkeit/iro
        build: ../iro
        container_name: iro-dashboard
        restart: always
        depends_on:
            - elasticsearch
        environment:
            ES_HOST: "elasticsearch"
            ES_PORT: "9200"
            TIM_URL: "https://fishy.xlab.si/tar/api/reports/v2"
            OICD_URL: "192.168.0.10:8443/auth/realms/fishy-realm/protocol/openid-connect/userinfo"
            CR_QUEUE_NAME: "IROQueue"
            CR_KEY: "reports.#"
            RABBIT_NOTIF_HOST: "fishymq.xlab.si"
            RABBIT_NOTIF_PORT : 45672
            RABBIT_NOTIF_EXCHANGE: "tasks"
            RABBIT_NOTIF_LOGIN: "tubs"
            RABBIT_NOTIF_PASS: "sbut"
            SC_QUEUE_NAME: "SCQueue"
            SC_KEY: "sc.validation"
            RABBIT_SC_EXCHANGE: "sc-results"
        ports:
            - "5000:5000"
        volumes:
            - /tmp:/edc
            - ./crt:/crt
        networks:
            - iro_lan

    elasticsearch:
        image: elasticsearch:7.14.2
        container_name: elasticsearch
        restart: always
        environment:
            - cluster.name=docker-cluster
            - node.name=elasticsearch1
            - cluster.initial_master_nodes=elasticsearch1
            - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
            - http.cors.enabled=true
            - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
            - http.cors.allow-credentials=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
                - "9200:9200"
        networks:
            - iro_lan
