apiVersion: v1
kind: Service
metadata:
  name: iro
  labels:
    service: iro
spec:
  selector:
    app: iro
  ports:
  - port: 5000
    nodePort: 30500
    targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iro
  labels:
    name: iro
spec:
  selector:
    matchLabels:
      app: iro
  replicas: 1
  template:
    metadata:
      labels:
        app: iro
      annotations:
        k8s.v1.cni.cncf.io/networks: vmgmtpod7@mgmt
    spec:
      containers:
      - name: iro
        image: michalkeit/iro:1.05
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /edc
          name: edc-volume
        env: 
        - name: INTERFACES_UP
          value: "mgmt:192.168.5.1/24"
        - name: ES_PORT
          value: "9200"
        - name: ES_HOST
          value: "iro-database"
        - name: TIM_HOST
          value: "192.168.55.10"
        - name: TIM_PORT
          value: "8000"
        - name: TIM_URL
          value: "https://fishy.xlab.si/tar/api/reports/v2"
        - name: OICD_URL
          value: "https://10.4.34.136:30443/auth/realms/fishy-realm/protocol/openid-connect/userinfo"
        - name: CR_QUEUE_NAME
          value: "IROQueue"
        - name: CR_KEY
          value: "reports.#"
        - name: RABBIT_NOTIF_HOST
          value: "fishymq.xlab.si"
        - name: RABBIT_NOTIF_PORT
          value: 45672
        - name: RABBIT_NOTIF_EXCHANGE
          value: "tasks"
        - name: RABBIT_NOTIF_LOGIN
          value: "tubs"
        - name: RABBIT_NOTIF_PASS
          value: "sbut"
        - name: SC_QUEUE_NAME
          value: "SCQueue"
        - name: SC_KEY
          value: "sc.validation"
        - name: RABBIT_SC_EXCHANGE
          value: "sc-results"
      volumes:
      - name: edc-volume
        hostPath:
        # directory location on host
          path: /tmp
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iro-elasticsearch
spec:
  selector:
    matchLabels:
      run: iro-elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        run: iro-elasticsearch
    spec:
      containers:
      - name: iro-elasticsearch
        image: elasticsearch:7.16.3
        ports:
        - containerPort: 9200
        env:
        - name: cluster.name
          value: "elasticsearch"
        - name: node.name
          value: "elasticsearch"
        - name: cluster.initial_master_nodes
          value: "elasticsearch"
        - name: http.cors.allow-origin
          value: "http://localhost:1358,http://127.0.0.1:1358"
        - name: http.cors.enabled
          value: "true"
        - name: http.cors.allow-headers
          value: "X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
        - name: http.cors.allow-credentials
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
---
apiVersion: v1
kind: Service
metadata:
  name: iro-database
  labels:
    run: iro-elasticsearch
spec:
  type: ClusterIP
  ports:
  - port: 9200
    protocol: TCP
  selector:
    run: iro-elasticsearch
